### ISSUE TITLE
Uninstallation instructions

### ISSUE THREAD

**Issue by 13am** [kees-z/DuplicatiDocs#10]
How do I uninstall Duplicati? Where are the uninstallation instructions? I'm using (Fedora) Linux. It would be useful to have the instructions in one place for all platforms!

**Comment by kees-z** [comment]
Does [this article](https://forum.duplicati.com/t/completely-removing-duplicati-for-re-install/3776/4) answer your questions? I'm not a regular Linux user, so I'm not sure how to write a plausible article for it.  
  
If you find out how to uninstall Duplicati completely from Linux systems, feel free to write an article and submit a PR.

**Comment by kees-z** [comment]
I assume that the article mentioned above anwers your question, so I'm closing this issue.
