### ISSUE TITLE
Duplicati Mono Dependency Errors on Ubuntu 24.04

### ISSUE THREAD

**Issue by Phoenix-Ignited-Tech** [kees-z/DuplicatiDocs#115]
When installing mono on Ubuntu 24.04.1 LTS noble I am getting the following errors: 
---------------------------
Package libappindicator0.1-cil is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libappindicator0.1-cil' has no installation candidate
---------------------------
And then when installing the duplicati .deb package I get similar errors regarding the missing packages: 
---------------------------
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'duplicati' instead of './duplicati_2.0.8.1-1_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 duplicati : Depends: libappindicator0.1-cil but it is not installable or
                      libappindicator3-0.1-cil but it is not installable or
                      libayatana-appindicator1 but it is not installable
E: Unable to correct problems, you have held broken packages. 
----------------------------------------------------------------------------------------------------------
I have attempted removing the packages and reinstalling them, same errors. 
Is there a known work around?
Thanks!

**Comment by kees-z** [comment]
This repository is for the documentation of Duplicati only.
If you have issues with using or installing Duplicati, open a new thread [here](https://forum.duplicati.com/).
