### ISSUE TITLE
404 error if I press "view" or "edit" in Duplicati documantation on website

### ISSUE THREAD

**Issue by vasili111** [kees-z/DuplicatiDocs#13]
I mean here: https://i.imgur.com/jlADh4T.png
Error received: https://i.imgur.com/EfBeLhp.png
Complete address in Chrome address bar: https://github.com/kees-z/DuplicatiDocs/edit/master/home/docs/checkouts/readthedocs.org/user_builds/duplicati/checkouts/latest/docs/03-using-the-graphical-user-interface.md

**Comment by kees-z** [comment]
The new [docs site](https://docs.duplicati.com) has a new theme that doesn't contain these links, so this issue can be closed.
