### ISSUE TITLE
Links in disaster recovery broken

### ISSUE THREAD

**Issue by vascotenner** [kees-z/DuplicatiDocs#33]
Links in disaster recovery broken:

https://duplicati.readthedocs.io/en/latest/08-disaster-recovery/

Not working:
* Restoring files from a backup
 * Restoring files if your Duplicati installation is lost

**Comment by kees-z** [comment]
Thanks for reporting this.
Unfortunately these links are not the only one, actually every link to another location in the docs was broken.
The links should work as soon as the date on the homepage is 2018/12/29.
There could be one or more links that I missed. Please report not working links if there are any.
