### ISSUE TITLE
WebDAV not listed under storage providers

### ISSUE THREAD

**Issue by magnific0** [kees-z/DuplicatiDocs#38]
I'm currently reviewing backup options and noticed that although WebDAV is used in this guide:
https://www.duplicati.com/articles/Getting-Started/#choose-how-to-add-the-backup

it isn't listed in the docs:
https://github.com/kees-z/DuplicatiDocs/blob/master/docs/05-storage-providers.md

Looking at the code it seems supported, so I'm not worried. As I haven't had any experience with the program so far, I'm raising this as an issue instead of a PR.

**Comment by kees-z** [comment]
Good catch!
I missed that one, thanks for reporting this.
Fixed.
