### ISSUE TITLE
Google Cloud Storage Classes don't seem correct

### ISSUE THREAD

**Issue by lukbukkit** [kees-z/DuplicatiDocs#44]
Hey,

I looked at this documentation and noticed the paramater `--gcs-storage-class` in the [Google Cloud](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#google-cloud-storage) section.

Is there an error, because I don't guess those regions are the storage class types?
If you confirm this error, I would create a pull request with the correct values.

Reference: https://cloud.google.com/storage/docs/storage-classes

**Comment by kees-z** [comment]
The documentation of the storage providers is directly copied from the internal help text of `Duplicati.CommandLine.exe`.
The command `Duplicati.CommandLine.exe help gcs` will give the same output.
If you find an issue in this text, please submit an issue at https://github.com/duplicati/duplicati/issues. This will fix the issue in the Duplicati binaries itself. Once fixed, the correct help text can be copied to the documentation. If I miss it, you can create a PR to get the documentation fixed.

**Comment by lukbukkit** [comment]
Okay thanks, I'll check and report the issuse to duplicati

**Comment by lukbukkit** [comment]
Here's the issue: https://github.com/duplicati/duplicati/issues/3857

**Comment by warwickmm** [comment]
The help text has been fixed in [#3680](https://github.com/duplicati/duplicati/pull/3860).
