### ISSUE TITLE
Some more typos in the doc

### ISSUE THREAD

**Issue by bugith** [kees-z/DuplicatiDocs#59]
Top of all pages : [Edit on squidfunk/mkdocs-material](https://github.com/squidfunk/mkdocs-material/edit/master/docs/03-using-the-graphical-user-interface.md) is a dead link  

[03-usingGUI/#creating-a-new-backup-job](https://duplicati.readthedocs.io/en/stable/03-using-the-graphical-user-interface/#creating-a-new-backup-job)
Last § before the Note : _...selecting Import from a file in the Add backup menu. **N** the next step you can browse..._ should be _...backup menu. **In** the next..._

[04-using-CLU](https://duplicati.readthedocs.io/en/stable/04-using-duplicati-from-the-command-line)
2 dead links to **Storage Providers** (was a chapter, moved to a [new page](https://duplicati.readthedocs.io/en/stable/05-storage-providers/))
1 dead link to **Advanced Options** (was a chapter, moved to a [dedicated page](https://duplicati.readthedocs.io/en/stable/06-advanced-options/))

[/07-other-CLU/#duplicaticommandlinerecoverytoolexe](https://duplicati.readthedocs.io/en/stable/07-other-command-line-utilities/#duplicaticommandlinerecoverytoolexe)
Dead link to **Disaster Recovery**  (was a chapter, moved to a [specific page](https://duplicati.readthedocs.io/en/stable/08-disaster-recovery/))

[08-Disaster recovery](https://duplicati.readthedocs.io/en/stable/08-disaster-recovery/):
_...problems it finds, but **is** there is significant damage_ should be _but **if** there is_

Great soft guys, keep on !

**Comment by kees-z** [comment]
I can't find any of the issues, it looks like you're viewing an [obsolete version](https://duplicati.readthedocs.io/en/stable/) of the documentation, please use the [current version](https://duplicati.readthedocs.io/en/latest/). The main link https://docs.duplicati.com redirects to the current version.

**Comment by bugith** [comment]
You're right, my links targeted the current version (stable) at the time of writing. Checking the (latest):
Top of all pages : "Edit on squidfunk/mkdocs-material" is a dead link => **seems fixed**
03-usingGUI/#creating-a-new-backup-job => **fixed**
04-using-CLU=> both dead links fixed. **On the left of the second one, an unintentional "<" appears.**
/07-other-CLU/#duplicaticommandlinerecoverytoolexe => **fixed**

I remember a guy sent a mail stating he was working on the (latest) not yet published at the time of writing.
