### ISSUE TITLE
Installation on Raspberry Pi Debian Buster

### ISSUE THREAD

**Issue by flurystefan** [kees-z/DuplicatiDocs#60]
Add this to the installationpart: 

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

echo "deb http://download.mono-project.com/repo/debian raspbianbuster main" | sudo tee /etc/apt/sources.list.d/mono-official.list

sudo apt-get update

sudo apt-get install mono-devel

unfortunately there was still a library missing and I forgot to write it down. But the message was clear

**Comment by kees-z** [comment]
Added to the installation section, thanks!
