### ISSUE TITLE
Add --full-report to "compare" documentation

### ISSUE THREAD

**Issue by Korkman** [kees-z/DuplicatiDocs#61]
Lists all added / removed / changed files instead of summarized version.

Also suited for 06-advanced-options.md

--verbose seems outdated, OTOH.

**Comment by kees-z** [comment]
I suppose you mean the `--full-result` option, it's added to the documentation of the `COMPARE` command.
`--full-result` was already included in the Advanced options section.
`--verbose` has similarities to `--full-result`, but isn't exactly the same. For example, `--verbose` lists passwords, `--full-result` does not.
