### ISSUE TITLE
Add reverse proxying tips

### ISSUE THREAD

**Issue by nicola-zanardi** [kees-z/DuplicatiDocs#63]
Based in [this issue](https://github.com/duplicati/duplicati/issues/1932) and my personal experience, it is a common requirement/desire to run the Duplicati WebUI behind a reverse proxy.

Would it be an idea to add this to the documentation? I can do it, I just need me pointers on which is the best section to add this to. At the end of the installation section could be an option.

Cheers,
Nicola

**Comment by kees-z** [comment]
Sure, the end of the Installation chapter looks like an obvious location. PR is appreciated!

**Comment by kees-z** [comment]
Closed because of inactivity.
