### ISSUE TITLE
Feature request: translations

### ISSUE THREAD

**Issue by wombalton** [kees-z/DuplicatiDocs#71]
Would be nice to make this informations available for non english speaking people.

I could help with a German translation.

**Comment by kees-z** [comment]
I like the idea of multi-language docs, but I'm not sure how to keep them all in sync and up-to-date.
You can of course fork this project and translate it in a separate project, but doesn't [Google Translate](https://translate.google.com/translate?sl=en&tl=de&u=https://docs.duplicati.com) work properly enough for you?
Feel free to reopen this issue if you have anything to add on this subject.

**Comment by luixxiul** [comment]
Using RST with Weblate could be one of the ways. For example, please see: https://github.com/onionshare/onionshare/tree/main/docs
