### ISSUE TITLE
Installation instructions for ubuntu are probably outdated

### ISSUE THREAD

**Issue by jfparis** [kees-z/DuplicatiDocs#75]
Hi

I was just reading the installation instruction for ubuntu on https://duplicati.readthedocs.io/en/latest/02-installation/

I noticed that the installation instructions were outdated for ubuntu 20.04 and I submitted a PR for that #74 
I believe that it should probably apply to older versions of ubuntu but I cannot verify this

**Comment by kees-z** [comment]
Merged, thanks for the update!
