### ISSUE TITLE
startup - another approach

### ISSUE THREAD

**Issue by tido-** [kees-z/DuplicatiDocs#76]
Hi, 
Thank you for the manual. First time user and I read it, before even downloaded.
However, it was kind of hard to understand the section with the startup and I was wondering if you're open for some suggestion
https://github.com/kees-z/DuplicatiDocs/blob/master/docs/02-installation.md

Cheers
Tido

**Comment by kees-z** [comment]
Yes, I'm always open to suggestions that can improve the documentation!

**Comment by tido-** [comment]
Great. I was thinking about this section: https://github.com/kees-z/DuplicatiDocs/blob/master/docs/02-installation.md#installing-duplicati-on-windows
I would give a short introduction to both options: user or service and remove this way the complexity as one can write only about the scenario chosen. If this sounds okay for you?

Apart from the above, mention or advice how to deal with this situation for the time being. I think it isn't in the manual as of now?: https://github.com/duplicati/duplicati/issues/3137#issuecomment-590853229

**Comment by kees-z** [comment]
Thanks for your input, sorry for the delay.

Regarding the user/service issue: I'm not sure if this is the right section for explaining these options. The concepts are explained at the beginning of the chapter, [right here](https://github.com/kees-z/DuplicatiDocs/blob/master/docs/02-installation.md#duplicati-components). If the difference between user- and service mode is explained in the "Installing Duplicati on Windows" section, Linux- and Apple-users might miss this information.
If you have an idea of how to explain the difference between a user- and service-based installation that apllies to users on all platforms, please post a suggestion or submit a pull request.

About the tray icon issue: thanks for pointing me to this in the first place! I missed this ons and was having the same problem for a long time. Now it is fixed and the tray icon works like a a charm.
This is a workaround for something that I think should work out of the box. Fixing this and making it work automatically should be the preferred action, but as long as this is an issue, I agree that an info block is useful.

**Comment by kees-z** [comment]
Closed because of lack of activity.
