### ISSUE TITLE
Request: Describe the commandline format

### ISSUE THREAD

**Issue by LordMike** [kees-z/DuplicatiDocs#78]
Hi,

I'm trying out duplicati for a linux server, and I was having trouble defining my setup. Turns out that arguments like `--webservice-port 8200` did not get read, they had to be in the form `--webservice-port=8200`.

I recommend adding that as a note in the top of [this page](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicatiserverexe), or maybe by adding examples to each commandline, like this:

![image](https://user-images.githubusercontent.com/1027111/122670677-7d8aac00-d1c3-11eb-9d8f-a872b0ca7b3c.png)

It would immediately highlight to the reader that the expected form is with an equals sign.

**Comment by kees-z** [comment]
The advanced options syntax applies to all command-line tools, not just the `Duplicati.Server.exe` tool. So I added an additional info block in the [Using Duplicati from the command line](https://github.com/kees-z/DuplicatiDocs/blob/master/docs/04-using-duplicati-from-the-command-line.md#how-to-use-the-duplicati-command-line-tool) section.
Hopefully this meets your needs. If not, feel free to reopen this issue.

**Comment by LordMike** [comment]
Definitely helps. :)
Thanks.
