### ISSUE TITLE
Request: Document log levels

### ISSUE THREAD

**Issue by LordMike** [kees-z/DuplicatiDocs#79]
As in another issue, I had some trouble deciphering why Duplicati was not reacting to my commandline. There was _no_ console output indicating an issue, so I turned to increasing the log level.

I tried the following, to get any output:

* `--log-level Debug`
* `--log-level 4`
* `--log-level dasfadsfdafs` <-- I expected an error in parsing the log level, which hopefully would provide me with valid values

I finally read the source code and found the [valid values here](https://github.com/duplicati/duplicati/blob/beaf03562fdcf4425e962085bdf7175d6a465f49/Duplicati/Library/Logging/Log.cs#L29-L63). 

For this request, I hope that these values could be documented such that future users won't have to guess :).

I'll also make an issue with Duplicati on outputting an error when invalid values are provided.

**Comment by kees-z** [comment]
Thanks for your input, docs updated: https://github.com/kees-z/DuplicatiDocs/compare/3ca9b3852d9bbae9d1016830b675c52a1e3213ce...4770388222f5e570b6377a7efc2884b207645c07
