### ISSUE TITLE
Document Docker installation and maintenance

### ISSUE THREAD

**Issue by warwickmm** [kees-z/DuplicatiDocs#81]
It would be helpful to document a basic Docker installation.  We should mention important details such as mapping volumes to [preserve configuration settings](https://hub.docker.com/r/duplicati/duplicati), and how to publish ports to provide access to the web interface.  There are some posts in the forums that summarize the basics pretty well.

https://forum.duplicati.com/t/how-to-install-duplicati-on-synology-dsm/5145

The Docker main page documents some of this (and more) already, and although it would duplicate the effort it would be nice if more of the documentation could be found in a single place.

**Comment by warwickmm** [comment]
This was motivated by https://github.com/duplicati/duplicati/issues/4564.

**Comment by brainchild0** [comment]
Further to the above, I would suggest that the main user documentation feature an explanation, preferably one highlighted by distinctive formatting, of each particular case where a user might be surprised by a Docker installation behaving differently from a regular one. Embedding these comments in the relevant locations of the main documentation offers a huge advantage over keeping them in entirely separate documentation. Some projects I have noticed attempt to keep a separate document for the Docker container, which explains the differences compared to a regular installation, but this structure tends to be confusing, by forcing users to rely at the same on different documents giving  inconsistent explanations.

**Comment by kees-z** [comment]
I'm not familiar with Docker. Please submit a proposal and suggest where to insert it in the current docs. Or even better, submit a PR. Valid PR's will be commited directly to the master branch.

**Comment by kees-z** [comment]
Closed because of lack of activity.
