### ISSUE TITLE
Documentation about database backups

### ISSUE THREAD

**Issue by tobias-graf-p** [kees-z/DuplicatiDocs#87]
I noticed that Duplicati is capable of taking database backups in the web application but didn't find **any** documentation about this feature at all.

Also I struggled configuring my backup job correctly on a server on which also a MS SQL Server is running until I found out that I have to add the Guid of the "SQL Server VSS Writer" to `--vss-exclude-writers`. Putting this Guid here prevents full backups of the SQL Server databases being triggered by the backup job (what would break the full-diff-log backup chain of a database maintained by SQL Server itself or by other tools). It would be great to cover this topic also in more detail in the docs.

**Comment by tobias-graf-p** [comment]
Note also [this thread](https://forum.duplicati.com/t/how-to-make-sql-server-vss-writer-make-copy-only-backups-via-duplicati/13712) where I am asking the community for their opinion for the idea to support more configuration options for the "SQL Server VSS Writer".

**Comment by kees-z** [comment]
Closing this one because of lack of activity and lack of substantive knowledge of this on my part.
