### ISSUE TITLE
Duplicati - Dropbox Backup - Replace short-lived token with no expiration

### ISSUE THREAD

**Issue by orappold** [kees-z/DuplicatiDocs#89]
Hi all,
I'm using Duplicati for my backups currently and I want to change y destination from Gdrive to Dropbox.

However it turns out, that apprently the OAUTH from Duplicati to Dropbox is not implemented properly as it only returns a SL (short-lived) token that expires after a couple of hours.

I haven't found a way to replace it with a proper token that doesn't expire. There is no config option in Duplicati itself and I tried to create my own app via Dropbox App Console.

I can hardly imagine that this behaviour is as expected? It would basically mean that there is no one out there, using Duplicati + Dropbox?

Code
Autorisation mit dem OAuth Service ist fehlgeschlagen: {"error_summary": "expired_access_token/.", "error": {".tag": "expired_access_token"}}.

Version: 2.0.6.2_experimental_2021-05-29 

Any help is much appreciated.

Thanks

**Comment by ts678** [comment]
This project is the Duplicati manual, so this would have been better put in the [duplicati project Issues](https://github.com/duplicati/duplicati/issues/), but there's one there now:

[\[Dropbox oauth\] expired_access_token error from Dropbox short-lived access tokens #4667](https://github.com/duplicati/duplicati/issues/4667)

I suppose there's a chance that the manual could explain how to solve/avoid this, but in my view it's more likely to take at least a configuration and possibly a code fix to the [oath-handler](https://github.com/duplicati/oauth-handler) project which technically has an Issues list, but it might not be watched.

I suggest you watch the above Duplicati issue and forum topic [Duplicati - Dropbox Backup - Short lived token expires](https://forum.duplicati.com/t/duplicati-dropbox-backup-short-lived-token-expires/13763) which may actually be your topic (based on looking at the similarity between original posts). Latest work is looking for workarounds for this.

**Comment by kees-z** [comment]
Agreed that the forums is the best place for discussing this problem.
